default: &default
  adapter: postgresql
  encoding: unicode
  pool: 25
  username: emerson
  password: 123456

development:
  <<: *default
  database: blog-esilvamg_development

test:
  <<: *default
  database: blog-esilvamg_test

production:
  <<: *default
  database: blog-esilvamg_production
